### ISSUE TITLE
Use headings, not bold text

### ISSUE THREAD

**Issue by adamn-ntap** [NetAppDocs/astra-automation#13]
Page: [Introduction to the Astra REST API](https://docs.netapp.com/us-en/astra-automation/intro/introduction.html)

The section "headings" on this page are not headings. They are simply boldface text at a larger font size. This means they cannot be linked to and there are no navigation links in the right-hand sidebar.

Change these to headings.

Making @netapp-bcammett and @dmp-netapp aware so there's consistency across the library.

**Comment by dmp-netapp** [comment]
Hi, I looked at the AsciiDoc source for the page. Actually these are headings (four =) and not bold text. The size and style seemed appropriate, given how little content each has. I could go up one level (three =) but this seems too large. Opinions?

**Comment by netapp-bcammett** [comment]
If it's meant to be a list of features, could you use a bulleted list instead?

**Comment by dmp-netapp** [comment]
It is a list of the major highlights and benefits, each of which has a couple of sentences of content. So I think using headers is more appropriate and looks good (to me at least). Have you taken a look?

https://docs.netapp.com/us-en/astra-automation/intro/introduction.html

**Comment by dmp-netapp** [comment]
Also, Adam was looking for consistency across the entire library (all the IE doc) and so I guess this would involve creating another rule for all the IE doc. In this case, what would the rule be? My view is there should be some flexibility regarding how to enumerate things depending on the content and context. Could be a bullet list or sections separated by headers or a table, and so on.

**Comment by netapp-bcammett** [comment]
Why not use level 2 headings?

**Comment by dmp-netapp** [comment]
I made the change to the headers. You can take a look at the URL below. I think it looks better.

https://review.docs.netapp.com/us-en/astra-automation_change-headers/

**Comment by netapp-bcammett** [comment]
It does look better. I would be curious to see what the page would look like with level 2 headers.

**Comment by dmp-netapp** [comment]
By level 2, you mean with two equal signs? My view is, when providing a list of things (in this case, a list of major product highlights or benefits), using this header is not appropriate. The header text is very large and there is a horizontal line beneath each header (establishing a clear division of the page into sections). And this is especially true when there is so little content after each header. I think this header is more for dividing a page into major sections. For example, when there are multiple tasks or multiple workflows on a page, this header is perfect. I can update the review site to see it. But again, when providing a list I don't think this header is the way to go.

**Comment by dmp-netapp** [comment]
We agreed that changing from the original four to three ='s looks better. So for now, I pushed this change out. The public site is live. When listing things, especially with a small amount of content, I think using L2 (two ='s) headers is not appropriate. But just for comparison I created another test branch. At the top are the eight features shown with L2 headers (including the larger text and horizontal line below). After that is the same content with the current L3 headers.

  https://review.docs.netapp.com/us-en/astra-automation_l2-headers/

I think it's important focus on two things. First, Adam said I should use headers and not bold text. I think this issue is closed because I am using headers. Also, if there is some suggested change to the page, maybe this can be formulated as general guidance or a rule from the architecture group.

**Comment by dmp-netapp** [comment]
As I said, I'm using headers on the introduction page and not bolded text. But changed from L4 to L3, which we agree looks better. Also propagated this change to the new Cloud Manager automation content. I am closing this issue, please create a new one if needed or maybe address this in the IE style guide. Thanks.
